/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserPermissionsRouteImport } from './routes/user-permissions'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as StaffRouteRouteImport } from './routes/staff/route'
import { Route as CompaniesRouteRouteImport } from './routes/companies/route'
import { Route as CategoriesRouteRouteImport } from './routes/categories/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as StaffStaffIdRouteImport } from './routes/staff/$staffId'
import { Route as CompaniesDashboardRouteImport } from './routes/companies/dashboard'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories/$categoryId'

const UserPermissionsRoute = UserPermissionsRouteImport.update({
  id: '/user-permissions',
  path: '/user-permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRouteRoute = CompaniesRouteRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRouteRoute = CategoriesRouteRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesRouteRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriesRouteRoute,
} as any)
const StaffStaffIdRoute = StaffStaffIdRouteImport.update({
  id: '/$staffId',
  path: '/$staffId',
  getParentRoute: () => StaffRouteRoute,
} as any)
const CompaniesDashboardRoute = CompaniesDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CompaniesRouteRoute,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => CategoriesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/companies': typeof CompaniesRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/user-permissions': typeof UserPermissionsRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/companies/dashboard': typeof CompaniesDashboardRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/user-permissions': typeof UserPermissionsRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/companies/dashboard': typeof CompaniesDashboardRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteRouteWithChildren
  '/companies': typeof CompaniesRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/user-permissions': typeof UserPermissionsRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/companies/dashboard': typeof CompaniesDashboardRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/companies'
    | '/staff'
    | '/dashboard'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/reports'
    | '/settings'
    | '/tags'
    | '/user-permissions'
    | '/categories/$categoryId'
    | '/companies/dashboard'
    | '/staff/$staffId'
    | '/categories/'
    | '/companies/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/reports'
    | '/settings'
    | '/tags'
    | '/user-permissions'
    | '/categories/$categoryId'
    | '/companies/dashboard'
    | '/staff/$staffId'
    | '/categories'
    | '/companies'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/companies'
    | '/staff'
    | '/dashboard'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/reports'
    | '/settings'
    | '/tags'
    | '/user-permissions'
    | '/categories/$categoryId'
    | '/companies/dashboard'
    | '/staff/$staffId'
    | '/categories/'
    | '/companies/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRouteRoute: typeof CategoriesRouteRouteWithChildren
  CompaniesRouteRoute: typeof CompaniesRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TagsRoute: typeof TagsRoute
  UserPermissionsRoute: typeof UserPermissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-permissions': {
      id: '/user-permissions'
      path: '/user-permissions'
      fullPath: '/user-permissions'
      preLoaderRoute: typeof UserPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof CompaniesRouteRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof CategoriesRouteRoute
    }
    '/staff/$staffId': {
      id: '/staff/$staffId'
      path: '/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof StaffStaffIdRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/companies/dashboard': {
      id: '/companies/dashboard'
      path: '/dashboard'
      fullPath: '/companies/dashboard'
      preLoaderRoute: typeof CompaniesDashboardRouteImport
      parentRoute: typeof CompaniesRouteRoute
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof CategoriesRouteRoute
    }
  }
}

interface CategoriesRouteRouteChildren {
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

const CategoriesRouteRouteChildren: CategoriesRouteRouteChildren = {
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}

const CategoriesRouteRouteWithChildren = CategoriesRouteRoute._addFileChildren(
  CategoriesRouteRouteChildren,
)

interface CompaniesRouteRouteChildren {
  CompaniesDashboardRoute: typeof CompaniesDashboardRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

const CompaniesRouteRouteChildren: CompaniesRouteRouteChildren = {
  CompaniesDashboardRoute: CompaniesDashboardRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}

const CompaniesRouteRouteWithChildren = CompaniesRouteRoute._addFileChildren(
  CompaniesRouteRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffStaffIdRoute: typeof StaffStaffIdRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffStaffIdRoute: StaffStaffIdRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRouteRoute: CategoriesRouteRouteWithChildren,
  CompaniesRouteRoute: CompaniesRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TagsRoute: TagsRoute,
  UserPermissionsRoute: UserPermissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
